webtalk_init -webtalk_dir C:/Users/wcockrum/COEN122/Pipeline_Buffer/Pipeline_Buffer.sim/sim_1/behav/xsim/xsim.dir/Buffer_TB_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Feb  1 15:00:04 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "176075600_1777486838_210724162_069" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "2233837d-2068-4681-8703-2ccaffc20398" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "a38b0b38db6645d2b70f33cbc3ab65bc" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Xeon(R) CPU E5-1620 v4 @ 3.50GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3492 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "34.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "100 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.06_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "7728_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2335250571 -regid "176075600_1777486838_210724162_069" -xml C:/Users/wcockrum/COEN122/Pipeline_Buffer/Pipeline_Buffer.sim/sim_1/behav/xsim/xsim.dir/Buffer_TB_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/wcockrum/COEN122/Pipeline_Buffer/Pipeline_Buffer.sim/sim_1/behav/xsim/xsim.dir/Buffer_TB_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/wcockrum/COEN122/Pipeline_Buffer/Pipeline_Buffer.sim/sim_1/behav/xsim/xsim.dir/Buffer_TB_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
